# src/docker-compose.yml
#
# Docker Compose configuration for Iroh project
# Mounts DAHDI devices from host system

version: '3.8'

services:
  iroh:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      # Mount just the DAHDI device directory
      - /dev/dahdi:/dev/dahdi:ro  # Read-only mount for safety
    ports:
      - "3000:3000"
    devices:
      # Map specific DAHDI devices
      - "/dev/dahdi/channel001:/dev/dahdi/channel001"
      - "/dev/dahdi/ctl:/dev/dahdi/ctl"
    # We still need some capabilities for direct device access
    cap_add:
      - SYS_RAWIO
    environment:
      - NODE_ENV=development
      - DAHDI_DEVICE=/dev/dahdi/channel001
      - DEBUG=iroh:*
      - LOG_LEVEL=debug
    command: sh -c "npm install && npm run dev"
    tty: true

  devtools:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
      - /dev/dahdi:/dev/dahdi:ro
    devices:
      - "/dev/dahdi/channel001:/dev/dahdi/channel001"
      - "/dev/dahdi/ctl:/dev/dahdi/ctl"
    cap_add:
      - SYS_RAWIO
    environment:
      - NODE_ENV=development
      - DAHDI_DEVICE=/dev/dahdi/channel001
      - DEBUG=iroh:*
      - LOG_LEVEL=debug
    command: /bin/sh
    tty: true