# File: iroh/config/commands.yml
# Command definitions and patterns for the Iroh Home Management System

commands:
  # Quick Timer Commands
  quick_timer:
    trigger: "digit"
    pattern: "single_digit"
    description: "Set quick timer (1-9 minutes)"
    enabled: true
    requires_confirmation: true
    handlers:
      - timer_manager.quick_timer
    
  # Service Control Commands
  service:
    trigger: "*"
    enabled: true
    patterns:
      - "*1": 
          action: "lights_on"
          service: "home_assistant"
          entity: "group.all_lights"
      - "*0": 
          action: "lights_off"
          service: "home_assistant"
          entity: "group.all_lights"
      - "*2XX": 
          action: "set_temperature"
          service: "home_assistant"
          entity: "climate.thermostat"
          pattern_vars:
            XX: "temperature"
    handlers:
      - home_assistant.handle_command
    
  # Voice Command Mode
  voice:
    trigger: "#"
    description: "Activate voice command mode"
    enabled: true
    timeout: 30  # seconds to wait for voice input
    handlers:
      - audio_service.start_voice_recognition
      - command_parser.parse_voice_command

# Command Categories
categories:
  timer:
    - quick_timer
    - custom_timer
  home_control:
    - lights
    - temperature
    - scenes
  system:
    - voice
    - status
    - debug

# Command Sequences
sequences:
  good_morning:
    trigger: "*11"
    actions:
      - lights_on:
          entity: "group.bedroom_lights"
          brightness: 50
      - wait: 300  # 5 minutes
      - lights_on:
          entity: "group.kitchen_lights"
      - set_temperature:
          value: 72

  good_night:
    trigger: "*00"
    actions:
      - lights_off:
          entity: "group.all_lights"
      - set_temperature:
          value: 68

# Error Handling
error_responses:
  invalid_command:
    audio: "Sorry, that command is not recognized"
    retry_allowed: true
    max_retries: 3
  
  timeout:
    audio: "Command timeout, please try again"
    retry_allowed: true
    max_retries: 2

  service_unavailable:
    audio: "Service is currently unavailable"
    retry_allowed: false
    notification: true

# Debug Commands (only available in debug mode)
debug_commands:
  status:
    trigger: "*99"
    description: "Get system status"
    handlers:
      - debug.get_status
  
  dump_state:
    trigger: "*98"
    description: "Dump current state"
    handlers:
      - debug.dump_state
